/*
* This file is part of the PX series horticulture appliance codebase (https://github.com/atsteen/PrimeBox).
* Copyright (c) 2017-2018 Sound Venture Group LLC.
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, version 3.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
* General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

#include "..\..\include\Viewstate_Map_Generator\Viewstate_Map_Generator_PX4.h"
#include "..\..\include\SharedStructure\SelectableNavigationMap.h"

Viewstate_Map_Generator_PX4::Viewstate_Map_Generator_PX4()
{
	GenerateMap(VIEWSTATEALIAS_STATUS_VIEW);
}

ISelectableNavigationMap * const Viewstate_Map_Generator_PX4::GenerateMap(const ViewstateAlias alias)
{
	if(_cachedMap && _cachedMap->CurrentSelection()->viewstate == alias) { return _cachedMap; }
	if(_cachedMap) { delete _cachedMap; }

	_cachedMap = new SelectableNavigationMap(alias);

	switch (alias) {
	case ViewstateAlias::VIEWSTATEALIAS_STATUS_VIEW:
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_ELEMENT_HIDDEN, VIEWSTATEALIAS_MANUAL_OVERRIDE_VIEW, SELECTABLE_BACK_ELEMENT);
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_ELEMENT_AUTO_REDIR, VIEWSTATEALIAS_MANUAL_OVERRIDE_VIEW_TLMV, SELECTABLE_ELEMENT_HIDDEN);
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_ELEMENT_AUTO_REDIR, VIEWSTATEALIAS_POWER_RELAY_SETTINGS_VIEW_TLMV, SELECTABLE_ELEMENT_HIDDEN);
		break;

	case ViewstateAlias::VIEWSTATEALIAS_MANUAL_OVERRIDE_VIEW_TLMV:
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_ELEMENT_HIDDEN, VIEWSTATEALIAS_MANUAL_OVERRIDE_VIEW, SELECTABLE_BACK_ELEMENT);
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_ELEMENT_AUTO_REDIR, VIEWSTATEALIAS_ENVIRONMENT_SETTINGS_VIEW_TLMV, SELECTABLE_ELEMENT_HIDDEN);
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_ELEMENT_AUTO_REDIR, VIEWSTATEALIAS_STATUS_VIEW, SELECTABLE_ELEMENT_HIDDEN);
		break;

	case ViewstateAlias::VIEWSTATEALIAS_MANUAL_OVERRIDE_VIEW:
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_BACK_ELEMENT, VIEWSTATEALIAS_MANUAL_OVERRIDE_VIEW_TLMV, SELECTABLE_ELEMENT_HIDDEN);
		_cachedMap->AddSelection(SELECTABLE_ELEMENT_DYNAMIC);
		break;

	case ViewstateAlias::VIEWSTATEALIAS_SCHEDULED_TASK_CONFIGURATION_VIEW_TLMV:
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_ELEMENT_HIDDEN, VIEWSTATEALIAS_SCHEDULED_TASK_CONFIGURATION_VIEW, SELECTABLE_BACK_ELEMENT);
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_ELEMENT_AUTO_REDIR, VIEWSTATEALIAS_POWER_RELAY_SETTINGS_VIEW_TLMV, SELECTABLE_ELEMENT_HIDDEN);
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_ELEMENT_AUTO_REDIR, VIEWSTATEALIAS_ENVIRONMENT_SETTINGS_VIEW_TLMV, SELECTABLE_ELEMENT_HIDDEN);
		break;

	case ViewstateAlias::VIEWSTATEALIAS_SCHEDULED_TASK_CONFIGURATION_VIEW:
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_BACK_ELEMENT, VIEWSTATEALIAS_SCHEDULED_TASK_CONFIGURATION_VIEW_TLMV, SELECTABLE_ELEMENT_HIDDEN);
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_MENU_SELECT_SCHD_TASK_SET_EXISTING_ELEMENT, VIEWSTATEALIAS_SCHEDULED_TASK_SET_EXISTING_VIEW, SELECTABLE_BACK_ELEMENT);
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_MENU_SELECT_SCHD_TASK_EDIT_EXISTING_ELEMENT, VIEWSTATEALIAS_SCHEDULED_TASK_EDIT_EXISTING_VIEW, SELECTABLE_BACK_ELEMENT);
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_MENU_SELECT_SCHD_TASK_CREATE_DELETE_ELEMENT, VIEWSTATEALIAS_SCHEDULED_TASK_CREATE_DELETE_VIEW, SELECTABLE_BACK_ELEMENT);
		break;

	case ViewstateAlias::VIEWSTATEALIAS_SCHEDULED_TASK_SET_EXISTING_VIEW:
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_BACK_ELEMENT, VIEWSTATEALIAS_SCHEDULED_TASK_CONFIGURATION_VIEW, SELECTABLE_MENU_SELECT_SCHD_TASK_SET_EXISTING_ELEMENT);
		_cachedMap->AddSelection(SELECTABLE_ELEMENT_DYNAMIC);
		break;

	case ViewstateAlias::VIEWSTATEALIAS_SCHEDULED_TASK_EDIT_EXISTING_VIEW:
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_BACK_ELEMENT, VIEWSTATEALIAS_SCHEDULED_TASK_CONFIGURATION_VIEW, SELECTABLE_MENU_SELECT_SCHD_TASK_EDIT_EXISTING_ELEMENT);
		_cachedMap->AddSelection(SELECTABLE_ELEMENT_DYNAMIC);
		break;

	case ViewstateAlias::VIEWSTATEALIAS_SCHEDULED_TASK_CREATE_DELETE_VIEW:
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_BACK_ELEMENT, VIEWSTATEALIAS_SCHEDULED_TASK_CONFIGURATION_VIEW, SELECTABLE_MENU_SELECT_SCHD_TASK_CREATE_DELETE_ELEMENT);
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_MENU_SELECT_NEW_SCHD_TASK_ELEMENT, VIEWSTATEALIAS_SCHEDULED_TASK_CREATE_TASK_VIEW, SELECTABLE_BACK_ELEMENT);
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_MENU_SELECT_DELETE_SCHD_TASK_ELEMENT, VIEWSTATEALIAS_SCHEDULED_TASK_DELETE_TASK_VIEW, SELECTABLE_BACK_ELEMENT);
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_MENU_SELECT_BULK_DELETE_SCHD_TASK_ELEMENT, VIEWSTATEALIAS_SCHEDULED_TASK_BULK_DELETE_TASK_CONF_VIEW, SELECTABLE_BACK_ELEMENT);
		break;

	case ViewstateAlias::VIEWSTATEALIAS_SCHEDULED_TASK_CREATE_TASK_VIEW:
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_BACK_ELEMENT, VIEWSTATEALIAS_SCHEDULED_TASK_CREATE_DELETE_VIEW, SELECTABLE_MENU_SELECT_NEW_SCHD_TASK_ELEMENT);
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_SCHEDULED_TASK_TASK_TARGET_ELEMENT, VIEWSTATEALIAS_SCHEDULED_TASK_CREATE_SELECT_VIEW, SELECTABLE_BACK_ELEMENT);
		_cachedMap->AddSelection(SELECTABLE_SCHEDULED_TASK_TASK_ACTION_ELEMENT);
		_cachedMap->AddSelection(SELECTABLE_SCHEDULED_TASK_TASK_TIME_ELEMENT);
		_cachedMap->AddSelection(SELECTABLE_SAVE_ELEMENT);
		break;

	case ViewstateAlias::VIEWSTATEALIAS_SCHEDULED_TASK_CREATE_SELECT_VIEW:
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_BACK_ELEMENT, VIEWSTATEALIAS_SCHEDULED_TASK_CREATE_TASK_VIEW, SELECTABLE_SCHEDULED_TASK_TASK_TARGET_ELEMENT);
		_cachedMap->AddSelection(SELECTABLE_SCHEDULED_TASK_CREATE_SELECT_BYRELAY_ELEMENT);
		_cachedMap->AddSelection(SELECTABLE_SCHEDULED_TASK_CREATE_SELECT_BYGROUP_ELEMENT);
		break;

	case ViewstateAlias::VIEWSTATEALIAS_SCHEDULED_TASK_CREATE_BY_RELAY_VIEW:
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_BACK_ELEMENT, VIEWSTATEALIAS_SCHEDULED_TASK_CREATE_SELECT_VIEW, SELECTABLE_BACK_ELEMENT);
		_cachedMap->AddSelection(SELECTABLE_SCHEDULED_TASK_CREATE_RELAY_TASK_ELEMENT);
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_SAVE_ELEMENT, VIEWSTATEALIAS_SCHEDULED_TASK_CREATE_TASK_VIEW, SELECTABLE_SCHEDULED_TASK_TASK_TARGET_ELEMENT);
		break;

	case ViewstateAlias::VIEWSTATEALIAS_SCHEDULED_TASK_CREATE_BY_ASSOCIATION_VIEW:
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_BACK_ELEMENT, VIEWSTATEALIAS_SCHEDULED_TASK_CREATE_SELECT_VIEW, SELECTABLE_BACK_ELEMENT);
		_cachedMap->AddSelection(SELECTABLE_SCHEDULED_TASK_CREATE_TYPE_TASK_ELEMENT);
		_cachedMap->AddSelection(SELECTABLE_SCHEDULED_TASK_CREATE_GROUP_TASK_ELEMENT);
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_SAVE_ELEMENT, VIEWSTATEALIAS_SCHEDULED_TASK_CREATE_TASK_VIEW, SELECTABLE_SCHEDULED_TASK_TASK_TARGET_ELEMENT);
		break;

	case ViewstateAlias::VIEWSTATEALIAS_SCHEDULED_TASK_DELETE_TASK_VIEW:
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_BACK_ELEMENT, VIEWSTATEALIAS_SCHEDULED_TASK_CREATE_DELETE_VIEW, SELECTABLE_MENU_SELECT_DELETE_SCHD_TASK_ELEMENT);
		_cachedMap->AddSelection(SELECTABLE_ELEMENT_DYNAMIC);
		break;

	case ViewstateAlias::VIEWSTATEALIAS_SCHEDULED_TASK_DELETE_TASK_CONF_VIEW:
		_cachedMap->AddSelection(SELECTABLE_BACK_ELEMENT);
		_cachedMap->AddSelection(SELECTABLE_SCHEDULED_TASK_DELETE_CONFYES_ELEMENT);
		_cachedMap->AddSelection(SELECTABLE_SCHEDULED_TASK_DELETE_CONFNO_ELEMENT);
		break;

	case ViewstateAlias::VIEWSTATEALIAS_SCHEDULED_TASK_BULK_DELETE_TASK_CONF_VIEW:
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_BACK_ELEMENT, VIEWSTATEALIAS_SCHEDULED_TASK_CREATE_DELETE_VIEW, SELECTABLE_MENU_SELECT_BULK_DELETE_SCHD_TASK_ELEMENT);
		_cachedMap->AddSelection(SELECTABLE_SCHEDULED_TASK_BULK_DELETE_CONFYES_ELEMENT);
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_SCHEDULED_TASK_BULK_DELETE_CONFNO_ELEMENT, VIEWSTATEALIAS_SCHEDULED_TASK_CREATE_DELETE_VIEW, SELECTABLE_MENU_SELECT_BULK_DELETE_SCHD_TASK_ELEMENT);
		break;

	case ViewstateAlias::VIEWSTATEALIAS_ENVIRONMENT_SETTINGS_VIEW_TLMV:
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_ELEMENT_HIDDEN, VIEWSTATEALIAS_ENVIRONMENT_SETTINGS_VIEW, SELECTABLE_BACK_ELEMENT);
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_ELEMENT_AUTO_REDIR, VIEWSTATEALIAS_SCHEDULED_TASK_CONFIGURATION_VIEW_TLMV, SELECTABLE_BACK_ELEMENT);
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_ELEMENT_AUTO_REDIR, VIEWSTATEALIAS_MANUAL_OVERRIDE_VIEW_TLMV, SELECTABLE_BACK_ELEMENT);
		break;

	case ViewstateAlias::VIEWSTATEALIAS_ENVIRONMENT_SETTINGS_VIEW:
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_BACK_ELEMENT, VIEWSTATEALIAS_ENVIRONMENT_SETTINGS_VIEW_TLMV, SELECTABLE_ELEMENT_HIDDEN);
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_MENU_SELECT_ENVIRONMENT_SUNRISE_SUNSET_ELEMENT, VIEWSTATEALIAS_ENVIRONMENT_SUNRISE_SUNSET_VIEW, SELECTABLE_BACK_ELEMENT);
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_MENU_SELECT_ENVIRONMENT_AIR_CIRC_ELEMENT, VIEWSTATEALIAS_ENVIRONMENT_AIR_CIRC_VIEW, SELECTABLE_BACK_ELEMENT);
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_MENU_SELECT_ENVIRONMENT_ALARM_THRESHOLDS_ELEMENT, VIEWSTATEALIAS_ENVIRONMENT_ALARM_THRESHOLDS_VIEW, SELECTABLE_BACK_ELEMENT);
		break;

	case ViewstateAlias::VIEWSTATEALIAS_ENVIRONMENT_SUNRISE_SUNSET_VIEW:
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_BACK_ELEMENT, VIEWSTATEALIAS_ENVIRONMENT_SETTINGS_VIEW, SELECTABLE_BACK_ELEMENT);
		_cachedMap->AddSelection(SELECTABLE_ENVIRONMENT_SUNRISE_SET_ELEMENT);
		_cachedMap->AddSelection(SELECTABLE_ENVIRONMENT_SUNSET_SET_ELEMENT);
		_cachedMap->AddSelection(SELECTABLE_ENVIRONMENT_SUN_CYCLE_SET_ELEMENT);
		break;

	case ViewstateAlias::VIEWSTATEALIAS_ENVIRONMENT_AIR_CIRC_VIEW:
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_BACK_ELEMENT, VIEWSTATEALIAS_ENVIRONMENT_SETTINGS_VIEW, SELECTABLE_BACK_ELEMENT);
		_cachedMap->AddSelection(SELECTABLE_ENVIRONMENT_FAN_CIRC_DAY_DUTY_SET_ELEMENT);
		_cachedMap->AddSelection(SELECTABLE_ENVIRONMENT_FAN_CIRC_NIGHT_DUTY_SET_ELEMENT);
		_cachedMap->AddSelection(SELECTABLE_ENVIRONMENT_FAN_CIRC_CYCLE_DURATION_SET_ELEMENT);
		_cachedMap->AddSelection(SELECTABLE_ENVIRONMENT_FAN_CIRC_CYCLE_MODE_SET_ELEMENT);
		_cachedMap->AddSelection(SELECTABLE_ENVIRONMENT_FAN_EX_DAY_DUTY_SET_ELEMENT);
		_cachedMap->AddSelection(SELECTABLE_ENVIRONMENT_FAN_EX_NIGHT_DUTY_SET_ELEMENT);
		_cachedMap->AddSelection(SELECTABLE_ENVIRONMENT_FAN_EX_CYCLE_DURATION_SET_ELEMENT);
		_cachedMap->AddSelection(SELECTABLE_ENVIRONMENT_FAN_EX_CYCLE_MODE_SET_ELEMENT);
		break;

	case ViewstateAlias::VIEWSTATEALIAS_ENVIRONMENT_ALARM_THRESHOLDS_VIEW:
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_BACK_ELEMENT, VIEWSTATEALIAS_ENVIRONMENT_SETTINGS_VIEW, SELECTABLE_BACK_ELEMENT);
		_cachedMap->AddSelection(SELECTABLE_ENVIRONMENT_OVERTEMP_ALARM_SET_ELEMENT);
		_cachedMap->AddSelection(SELECTABLE_ENVIRONMENT_OVERHUM_ALARM_SET_ELEMENT);
		_cachedMap->AddSelection(SELECTABLE_ENVIRONMENT_LOGFULL_ALARM_SET_ELEMENT);
		break;

	case ViewstateAlias::VIEWSTATEALIAS_POWER_RELAY_SETTINGS_VIEW_TLMV:
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_ELEMENT_HIDDEN, VIEWSTATEALIAS_POWER_RELAY_SETTINGS_VIEW, SELECTABLE_BACK_ELEMENT);
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_ELEMENT_AUTO_REDIR, VIEWSTATEALIAS_STATUS_VIEW, SELECTABLE_ELEMENT_HIDDEN);
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_ELEMENT_AUTO_REDIR, VIEWSTATEALIAS_SCHEDULED_TASK_CONFIGURATION_VIEW_TLMV, SELECTABLE_ELEMENT_HIDDEN);
		break;

	case ViewstateAlias::VIEWSTATEALIAS_POWER_RELAY_SETTINGS_VIEW:
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_BACK_ELEMENT, VIEWSTATEALIAS_POWER_RELAY_SETTINGS_VIEW_TLMV, SELECTABLE_ELEMENT_HIDDEN);
		_cachedMap->AddSelection(SELECTABLE_ELEMENT_DYNAMIC);
		break;

	case ViewstateAlias::VIEWSTATEALIAS_POWER_RELAY_EDIT_VIEW :
		_cachedMap->AddSelection(SELECTABLE_BACK_ELEMENT);
		_cachedMap->AddSelection(SELECTABLE_EDIT_RELAY_TYPE);
		_cachedMap->AddSelection(SELECTABLE_EDIT_RELAY_GROUP);
		break;

	case ViewstateAlias::VIEWSTATEALIAS_INPUT_PROMPT_TIME:
		_cachedMap->AddSelection(SELECTABLE_BACK_ELEMENT);
		_cachedMap->AddSelection(SELECTABLE_SETTIME_HH_ELEMENT);
		_cachedMap->AddSelection(SELECTABLE_SETTIME_MM_ELEMENT);
		_cachedMap->AddSelection(SELECTABLE_SAVE_ELEMENT);
		break;

	case ViewstateAlias::VIEWSTATEALIAS_INPUT_PROMPT_THREESEGMENT:
		_cachedMap->AddSelection(SELECTABLE_BACK_ELEMENT);
		_cachedMap->AddSelection(SELECTABLE_SETTHREESEGMENTVALUE_ELEMENT);
		_cachedMap->AddSelection(SELECTABLE_SAVE_ELEMENT);
		break;

	case ViewstateAlias::VIEWSTATEALIAS_INPUT_PROMPT_BOOLEAN_ENABLE_DISABLE:
	case ViewstateAlias::VIEWSTATEALIAS_INPUT_PROMPT_BOOLEAN_ON_OFF:
		_cachedMap->AddSelection(SELECTABLE_BACK_ELEMENT);
		_cachedMap->AddSelection(SELECTABLE_SETBOOLEANVALUE_ELEMENT);
		_cachedMap->AddSelection(SELECTABLE_SAVE_ELEMENT);
		break;

	default:		
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_ELEMENT_HIDDEN, VIEWSTATEALIAS_MANUAL_OVERRIDE_VIEW, SELECTABLE_BACK_ELEMENT);
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_ELEMENT_AUTO_REDIR, VIEWSTATEALIAS_MANUAL_OVERRIDE_VIEW_TLMV, SELECTABLE_ELEMENT_HIDDEN);
		_cachedMap->AddSelectionWithRedirect(SELECTABLE_ELEMENT_AUTO_REDIR, VIEWSTATEALIAS_ENVIRONMENT_SETTINGS_VIEW_TLMV, SELECTABLE_ELEMENT_HIDDEN);
		break;
	}

	return _cachedMap;
}
