/*
* This file is part of the PX series horticulture appliance codebase (https://github.com/atsteen/PrimeBox).
* Copyright (c) 2017-2018 Sound Venture Group LLC.
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, version 3.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
* General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

#pragma once

enum ViewstateAlias {
	VIEWSTATEALIAS_NOT_SET,
	VIEWSTATEALIAS_STATUS_VIEW,

	VIEWSTATEALIAS_MANUAL_OVERRIDE_VIEW_TLMV,
	VIEWSTATEALIAS_MANUAL_OVERRIDE_VIEW,

	VIEWSTATEALIAS_POWER_RELAY_SETTINGS_VIEW_TLMV,
	VIEWSTATEALIAS_POWER_RELAY_SETTINGS_VIEW,
	VIEWSTATEALIAS_POWER_RELAY_EDIT_VIEW,

	VIEWSTATEALIAS_SCHEDULED_TASK_CONFIGURATION_VIEW_TLMV,
	VIEWSTATEALIAS_SCHEDULED_TASK_CONFIGURATION_VIEW,
	VIEWSTATEALIAS_SCHEDULED_TASK_SET_EXISTING_VIEW,
	VIEWSTATEALIAS_SCHEDULED_TASK_EDIT_EXISTING_VIEW,
	VIEWSTATEALIAS_SCHEDULED_TASK_CREATE_DELETE_VIEW,
	VIEWSTATEALIAS_SCHEDULED_TASK_CREATE_TASK_VIEW,
	VIEWSTATEALIAS_SCHEDULED_TASK_CREATE_SELECT_VIEW,
	VIEWSTATEALIAS_SCHEDULED_TASK_CREATE_BY_RELAY_VIEW,
	VIEWSTATEALIAS_SCHEDULED_TASK_CREATE_BY_ASSOCIATION_VIEW,
	VIEWSTATEALIAS_SCHEDULED_TASK_DELETE_TASK_VIEW,
	VIEWSTATEALIAS_SCHEDULED_TASK_DELETE_TASK_CONF_VIEW,
	VIEWSTATEALIAS_SCHEDULED_TASK_BULK_DELETE_TASK_CONF_VIEW,

	VIEWSTATEALIAS_ENVIRONMENT_SETTINGS_VIEW_TLMV,
	VIEWSTATEALIAS_ENVIRONMENT_SETTINGS_VIEW,
	VIEWSTATEALIAS_ENVIRONMENT_SUNRISE_SUNSET_VIEW,
	VIEWSTATEALIAS_ENVIRONMENT_AIR_CIRC_VIEW,
	VIEWSTATEALIAS_ENVIRONMENT_ALARM_THRESHOLDS_VIEW,

	VIEWSTATEALIAS_INPUT_PROMPT_TIME,
	VIEWSTATEALIAS_INPUT_PROMPT_BOOLEAN_ENABLE_DISABLE,
	VIEWSTATEALIAS_INPUT_PROMPT_BOOLEAN_ON_OFF,
	VIEWSTATEALIAS_INPUT_PROMPT_THREESEGMENT
};